- hosts: all
  vars_files:
    - ../variables.yml
  tasks:
    - import_tasks: tasks/00_halyard.yml
      tags: halyard

    - import_tasks: tasks/01_docker.yml
      tags: docker

    - import_tasks: tasks/02_minio.yml
      tags: minio

    - import_tasks: tasks/03_deploy.yml
      tags: deploy
